import { db } from "@/db";
import { opportunities, archetypes } from "@/db/schema";
import type { Requirement } from "@/modules/eligibility/types";

export const SEED_OPPORTUNITIES: {
  id?: string;
  kind: "govt_post" | "scheme";
  title: string;
  department: string;
  state: string;
  status: "live" | "draft";
  closesOn?: Date;
  requirements: Requirement[];
  sourceDocumentPath?: string;
}[] = [
  {
    kind: "govt_post",
    title: "MPPSC State Services Examination 2026",
    department: "Madhya Pradesh Public Service Commission, Indore",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-12-31T23:59:59Z"),
    sourceDocumentPath: "notifications/mppsc_sse_2026.pdf",
    requirements: [
      {
        id: "mppsc-age-min",
        kind: "age",
        op: "min",
        value: 21,
        blocking: true,
        weight: 10,
        label: "Minimum Age 21 Years",
        source: {
          type: "notification",
          clause: "Clause 3(a)",
          page: 4,
          documentId: "mppsc-sse-2026",
        },
      },
      {
        id: "mppsc-age-cap",
        kind: "age",
        op: "max",
        value: 33,
        overrides: [
          { whenCategory: "SC", value: 38 },
          { whenCategory: "ST", value: 38 },
          { whenCategory: "OBC", value: 38 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 33 (General), 38 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 3(b) & MP State Relaxation Order 2023",
          page: 5,
          documentId: "mppsc-sse-2026",
        },
      },
      {
        id: "mppsc-qualification",
        kind: "qualification",
        op: "one_of",
        value: [
          "graduate",
          "b.tech",
          "b.e",
          "b.sc",
          "b.a",
          "b.com",
          "bca",
          "llb",
          "post_graduate",
        ],
        blocking: true,
        weight: 10,
        label: "Graduation Degree from a Recognized University",
        source: {
          type: "notification",
          clause: "Clause 4.1",
          page: 6,
          documentId: "mppsc-sse-2026",
        },
      },
      {
        id: "mppsc-gk-mp",
        kind: "skill",
        op: "has",
        value: "Madhya Pradesh General Knowledge",
        blocking: false,
        weight: 9,
        label: "Madhya Pradesh History, Geography & Governance",
        source: {
          type: "notification",
          clause: "Syllabus Paper I",
          page: 12,
          documentId: "mppsc-sse-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP Police Constable Recruitment 2026",
    department: "Madhya Pradesh Police Headquarters, Bhopal",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-11-30T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_police_constable_2026.pdf",
    requirements: [
      {
        id: "mp-police-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Bona-fide Resident of Madhya Pradesh",
        source: {
          type: "notification",
          clause: "Clause 1.2",
          page: 2,
          documentId: "mp-police-constable-2026",
        },
      },
      {
        id: "mp-police-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mp-police-constable-2026",
        },
      },
      {
        id: "mp-police-age-cap",
        kind: "age",
        op: "max",
        value: 28,
        overrides: [
          { whenCategory: "SC", value: 33 },
          { whenCategory: "ST", value: 33 },
          { whenCategory: "OBC", value: 33 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 28 (General), 33 (Reserved Categories)",
        source: {
          type: "notification",
          clause: "Clause 2.2",
          page: 3,
          documentId: "mp-police-constable-2026",
        },
      },
      {
        id: "mp-police-fitness",
        kind: "skill",
        op: "has",
        value: "Physical Fitness",
        blocking: false,
        weight: 8,
        label: "Physical Endurance and Fitness Standards",
        source: {
          type: "notification",
          clause: "Clause 5.4",
          page: 8,
          documentId: "mp-police-constable-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP Patwari Recruitment Examination 2026",
    department: "Department of Revenue, Government of Madhya Pradesh",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-12-15T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_patwari_2026.pdf",
    requirements: [
      {
        id: "patwari-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Madhya Pradesh Domicile Required",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mp-patwari-2026",
        },
      },
      {
        id: "patwari-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 4,
          documentId: "mp-patwari-2026",
        },
      },
      {
        id: "patwari-age-cap",
        kind: "age",
        op: "max",
        value: 40,
        overrides: [
          { whenCategory: "SC", value: 45 },
          { whenCategory: "ST", value: 45 },
          { whenCategory: "OBC", value: 45 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 40 (General), 45 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 3.2 & MP GAD Notification 2022",
          page: 4,
          documentId: "mp-patwari-2026",
        },
      },
      {
        id: "patwari-degree",
        kind: "qualification",
        op: "one_of",
        value: [
          "graduate",
          "b.a",
          "b.sc",
          "b.com",
          "b.tech",
          "b.e",
          "bca",
          "post_graduate",
        ],
        blocking: true,
        weight: 10,
        label: "Bachelor Degree in Any Stream",
        source: {
          type: "notification",
          clause: "Clause 4.1",
          page: 5,
          documentId: "mp-patwari-2026",
        },
      },
      {
        id: "patwari-cpct",
        kind: "skill",
        op: "has",
        value: "CPCT Scorecard",
        blocking: false,
        weight: 8,
        label: "CPCT Scorecard with Hindi Typing Proficiency",
        source: {
          type: "notification",
          clause: "Clause 4.2",
          page: 5,
          documentId: "mp-patwari-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP ESB Sub-Engineer (Civil) Recruitment 2026",
    department: "Urban Development & Housing Department, MP",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-11-20T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_sub_engineer_2026.pdf",
    requirements: [
      {
        id: "subeng-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Resident of Madhya Pradesh (Rojgar Panjiyan Required)",
        source: {
          type: "notification",
          clause: "Clause 1.3",
          page: 2,
          documentId: "mp-subeng-2026",
        },
      },
      {
        id: "subeng-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mp-subeng-2026",
        },
      },
      {
        id: "subeng-age-cap",
        kind: "age",
        op: "max",
        value: 40,
        overrides: [
          { whenCategory: "SC", value: 45 },
          { whenCategory: "ST", value: 45 },
          { whenCategory: "OBC", value: 45 },
        ],
        blocking: true,
        weight: 10,
        label: "Max Age Cap: 40 (General), 45 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 2.2",
          page: 3,
          documentId: "mp-subeng-2026",
        },
      },
      {
        id: "subeng-qualification",
        kind: "qualification",
        op: "one_of",
        value: ["diploma civil", "b.tech civil", "b.e civil"],
        blocking: true,
        weight: 10,
        label: "3-Year Diploma or B.E./B.Tech in Civil Engineering",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 4,
          documentId: "mp-subeng-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP Vanrakshak (Forest Guard) Recruitment 2026",
    department: "Madhya Pradesh Forest Department, Bhopal",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-10-31T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_vanrakshak_2026.pdf",
    requirements: [
      {
        id: "vanrakshak-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Domicile of Madhya Pradesh",
        source: {
          type: "notification",
          clause: "Clause 1.2",
          page: 2,
          documentId: "mp-vanrakshak-2026",
        },
      },
      {
        id: "vanrakshak-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mp-vanrakshak-2026",
        },
      },
      {
        id: "vanrakshak-age-cap",
        kind: "age",
        op: "max",
        value: 33,
        overrides: [
          { whenCategory: "SC", value: 38 },
          { whenCategory: "ST", value: 38 },
          { whenCategory: "OBC", value: 38 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 33 (UR), 38 (Reserved Categories)",
        source: {
          type: "notification",
          clause: "Clause 2.3",
          page: 3,
          documentId: "mp-vanrakshak-2026",
        },
      },
      {
        id: "vanrakshak-qualification",
        kind: "qualification",
        op: "one_of",
        value: ["10+2", "12th", "higher secondary", "graduate"],
        blocking: true,
        weight: 10,
        label: "10+2 Higher Secondary Pass (12th Standard)",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 4,
          documentId: "mp-vanrakshak-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP High Court Junior Judicial Assistant 2026",
    department: "High Court of Madhya Pradesh, Jabalpur",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-12-20T23:59:59Z"),
    sourceDocumentPath: "notifications/mphc_jja_2026.pdf",
    requirements: [
      {
        id: "mphc-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 3,
          documentId: "mphc-jja-2026",
        },
      },
      {
        id: "mphc-age-cap",
        kind: "age",
        op: "max",
        value: 35,
        overrides: [
          { whenCategory: "SC", value: 40 },
          { whenCategory: "ST", value: 40 },
          { whenCategory: "OBC", value: 40 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 35 (General), 40 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 3.3",
          page: 3,
          documentId: "mphc-jja-2026",
        },
      },
      {
        id: "mphc-qualification",
        kind: "qualification",
        op: "one_of",
        value: [
          "graduate",
          "b.a",
          "b.sc",
          "b.com",
          "b.tech",
          "llb",
          "post_graduate",
        ],
        blocking: true,
        weight: 10,
        label: "Graduation Degree in any Discipline",
        source: {
          type: "notification",
          clause: "Clause 4.1",
          page: 4,
          documentId: "mphc-jja-2026",
        },
      },
      {
        id: "mphc-typing",
        kind: "skill",
        op: "has",
        value: "English Typing 80 WPM",
        blocking: false,
        weight: 9,
        label: "English Typing Speed Certificate (80 WPM)",
        source: {
          type: "notification",
          clause: "Clause 4.2",
          page: 4,
          documentId: "mphc-jja-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP NHM Staff Nurse & ANM Recruitment 2026",
    department: "National Health Mission, Health Department MP",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-11-15T23:59:59Z"),
    sourceDocumentPath: "notifications/nhm_staff_nurse_2026.pdf",
    requirements: [
      {
        id: "nhm-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Bona-fide Resident of Madhya Pradesh",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 2,
          documentId: "nhm-nurse-2026",
        },
      },
      {
        id: "nhm-age-min",
        kind: "age",
        op: "min",
        value: 21,
        blocking: true,
        weight: 10,
        label: "Minimum Age 21 Years",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 3,
          documentId: "nhm-nurse-2026",
        },
      },
      {
        id: "nhm-age-cap",
        kind: "age",
        op: "max",
        value: 43,
        overrides: [
          { whenCategory: "SC", value: 48 },
          { whenCategory: "ST", value: 48 },
          { whenCategory: "OBC", value: 48 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 43 (General), 48 (SC/ST/OBC/Female)",
        source: {
          type: "notification",
          clause: "Clause 3.2 & Health Dept Circular",
          page: 3,
          documentId: "nhm-nurse-2026",
        },
      },
      {
        id: "nhm-nursing-degree",
        kind: "qualification",
        op: "one_of",
        value: ["b.sc nursing", "gnm", "post basic b.sc nursing"],
        blocking: true,
        weight: 10,
        label: "B.Sc. Nursing or GNM from Recognized Institute",
        source: {
          type: "notification",
          clause: "Clause 4.1",
          page: 4,
          documentId: "nhm-nurse-2026",
        },
      },
      {
        id: "nhm-council-reg",
        kind: "certification",
        op: "has",
        value: "MP Nursing Council Registration",
        blocking: true,
        weight: 10,
        label: "Live Registration in Madhya Pradesh Nursing Council",
        source: {
          type: "notification",
          clause: "Clause 4.3",
          page: 4,
          documentId: "nhm-nurse-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MPPGCL Assistant Engineer (Electrical) 2026",
    department: "MP Power Generating Company Limited, Jabalpur",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-12-10T23:59:59Z"),
    sourceDocumentPath: "notifications/mppgcl_ae_2026.pdf",
    requirements: [
      {
        id: "mppgcl-age-min",
        kind: "age",
        op: "min",
        value: 21,
        blocking: true,
        weight: 10,
        label: "Minimum Age 21 Years",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mppgcl-ae-2026",
        },
      },
      {
        id: "mppgcl-age-cap",
        kind: "age",
        op: "max",
        value: 40,
        overrides: [
          { whenCategory: "SC", value: 45 },
          { whenCategory: "ST", value: 45 },
          { whenCategory: "OBC", value: 45 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 40 (General), 45 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 2.2",
          page: 3,
          documentId: "mppgcl-ae-2026",
        },
      },
      {
        id: "mppgcl-degree",
        kind: "qualification",
        op: "one_of",
        value: ["b.tech electrical", "b.e electrical", "b.tech eee", "b.e eee"],
        blocking: true,
        weight: 10,
        label: "B.E./B.Tech in Electrical Engineering with Min 65% Marks",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 4,
          documentId: "mppgcl-ae-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP Tourism Assistant Manager 2026",
    department: "Madhya Pradesh Tourism Board, Bhopal",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-11-28T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_tourism_am_2026.pdf",
    requirements: [
      {
        id: "mpt-age-min",
        kind: "age",
        op: "min",
        value: 21,
        blocking: true,
        weight: 10,
        label: "Minimum Age 21 Years",
        source: {
          type: "notification",
          clause: "Clause 1.4",
          page: 2,
          documentId: "mpt-2026",
        },
      },
      {
        id: "mpt-age-cap",
        kind: "age",
        op: "max",
        value: 40,
        overrides: [
          { whenCategory: "SC", value: 45 },
          { whenCategory: "ST", value: 45 },
          { whenCategory: "OBC", value: 45 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 40 (UR), 45 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 1.5",
          page: 2,
          documentId: "mpt-2026",
        },
      },
      {
        id: "mpt-degree",
        kind: "qualification",
        op: "one_of",
        value: [
          "mba tourism",
          "mba marketing",
          "post graduate diploma tourism",
          "graduate",
        ],
        blocking: true,
        weight: 10,
        label: "Post Graduate / MBA in Tourism or Hospitality Management",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mpt-2026",
        },
      },
    ],
  },
  {
    kind: "govt_post",
    title: "MP ESB Group-4 Assistant Grade-3 / Typist 2026",
    department: "Madhya Pradesh Staff Selection Board (ESB), Bhopal",
    state: "Madhya Pradesh",
    status: "live",
    closesOn: new Date("2026-12-05T23:59:59Z"),
    sourceDocumentPath: "notifications/mp_group4_ag3_2026.pdf",
    requirements: [
      {
        id: "ag3-domicile",
        kind: "domicile",
        op: "equals",
        value: "Madhya Pradesh",
        blocking: true,
        weight: 10,
        label: "Madhya Pradesh Domicile & Active Rojgar Registration",
        source: {
          type: "notification",
          clause: "Clause 1.2",
          page: 2,
          documentId: "mp-group4-2026",
        },
      },
      {
        id: "ag3-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: {
          type: "notification",
          clause: "Clause 2.1",
          page: 3,
          documentId: "mp-group4-2026",
        },
      },
      {
        id: "ag3-age-cap",
        kind: "age",
        op: "max",
        value: 40,
        overrides: [
          { whenCategory: "SC", value: 45 },
          { whenCategory: "ST", value: 45 },
          { whenCategory: "OBC", value: 45 },
        ],
        blocking: true,
        weight: 10,
        label: "Maximum Age Cap: 40 (General), 45 (SC/ST/OBC)",
        source: {
          type: "notification",
          clause: "Clause 2.3",
          page: 3,
          documentId: "mp-group4-2026",
        },
      },
      {
        id: "ag3-qualification",
        kind: "qualification",
        op: "one_of",
        value: ["10+2", "12th", "higher secondary", "graduate"],
        blocking: true,
        weight: 10,
        label: "10+2 Higher Secondary Pass",
        source: {
          type: "notification",
          clause: "Clause 3.1",
          page: 4,
          documentId: "mp-group4-2026",
        },
      },
      {
        id: "ag3-cpct",
        kind: "skill",
        op: "has",
        value: "CPCT Hindi Typing",
        blocking: true,
        weight: 10,
        label: "CPCT Scorecard with Hindi Typing Passed",
        source: {
          type: "notification",
          clause: "Clause 3.2",
          page: 4,
          documentId: "mp-group4-2026",
        },
      },
    ],
  },
];

export const SEED_ARCHETYPES: {
  title: string;
  requirements: Requirement[];
}[] = [
  {
    title: "Junior Software Engineer",
    requirements: [
      {
        id: "arch-swe-degree",
        kind: "qualification",
        op: "one_of",
        value: ["b.tech", "b.e", "bca", "mca", "b.sc computer science"],
        blocking: true,
        weight: 10,
        label: "Computer Science or Related Technical Degree",
        source: { type: "archetype", note: "Standard entry bar" },
      },
      {
        id: "arch-swe-python",
        kind: "skill",
        op: "has",
        value: "Python",
        blocking: false,
        weight: 8,
        label: "Python Programming",
        source: {
          type: "interview_evidence",
          sampleSize: 20,
          matchCount: 16,
        },
      },
      {
        id: "arch-swe-sql",
        kind: "skill",
        op: "has",
        value: "SQL",
        blocking: false,
        weight: 7,
        label: "Relational Database & SQL",
        source: {
          type: "interview_evidence",
          sampleSize: 15,
          matchCount: 12,
        },
      },
    ],
  },
  {
    title: "Administrative Assistant",
    requirements: [
      {
        id: "arch-admin-age-min",
        kind: "age",
        op: "min",
        value: 18,
        blocking: true,
        weight: 10,
        label: "Minimum Age 18 Years",
        source: { type: "archetype", note: "Labor law legal age" },
      },
      {
        id: "arch-admin-office",
        kind: "skill",
        op: "has",
        value: "Office Tools",
        blocking: false,
        weight: 9,
        label: "MS Office / Google Docs & Spreadsheets",
        source: { type: "archetype", note: "Essential office operations" },
      },
      {
        id: "arch-admin-typing",
        kind: "skill",
        op: "has",
        value: "Typing Speed",
        blocking: false,
        weight: 8,
        label: "Typing Speed (Hindi / English 30 WPM)",
        source: { type: "archetype", note: "Standard administrative speed" },
      },
    ],
  },
];

/**
 * Idempotently seeds initial opportunities and archetypes into the database using batched operations.
 */
export async function seedEligibilityData() {
  const [existingOpps, existingArchs] = await Promise.all([
    db.select().from(opportunities),
    db.select().from(archetypes),
  ]);

  const oppTitles = new Set(existingOpps.map((o) => o.title));
  const archTitles = new Set(existingArchs.map((a) => a.title));

  const oppsToInsert = SEED_OPPORTUNITIES.filter(
    (o) => !oppTitles.has(o.title),
  );
  const archsToInsert = SEED_ARCHETYPES.filter((a) => !archTitles.has(a.title));

  const [newOpps, newArchs] = await Promise.all([
    oppsToInsert.length > 0
      ? db
          .insert(opportunities)
          .values(
            oppsToInsert.map((opp) => ({
              kind: opp.kind,
              title: opp.title,
              department: opp.department,
              state: opp.state,
              status: opp.status,
              closesOn: opp.closesOn,
              requirements: opp.requirements,
              sourceDocumentPath: opp.sourceDocumentPath,
            })),
          )
          .returning()
      : Promise.resolve([]),
    archsToInsert.length > 0
      ? db.insert(archetypes).values(archsToInsert).returning()
      : Promise.resolve([]),
  ]);

  return {
    opportunities: [...existingOpps, ...newOpps],
    archetypes: [...existingArchs, ...newArchs],
  };
}
